
Trying to 

```{r}
library(tidyverse)
library(stringr)
library(lubridate)
thead <- function(x) {return(head(data.frame(x)))}
```



```{r}

bbmSales <- read_csv("square sales data project aug 2017.csv")

thead(bbmSales)

bbmSales <- bbmSales %>% 
  mutate(NetSales=as.numeric(sub("\\$","",`Net Sales`))) %>%
  mutate(GrossSales=as.numeric(sub("\\$","",`Gross Sales`))) %>%
  mutate(Discounts=as.numeric(sub("\\$","",`Discounts`)))%>%
  mutate(DateString=str_c(Date,"_",Time))%>%
  group_by(DateString,`Time Zone`)%>%
  mutate(DateTime=parse_date_time(DateString,"m/d/y_h:M:S",
    tz=unique(`Time Zone`)))%>%
  ungroup()%>%
  mutate(DateTime=with_tz(DateTime,tzone="America/Los_Angeles"))%>%
  mutate(DayOfWeek=wday(DateTime))%>%
  mutate(DayOfYear=yday(DateTime))%>%
  mutate(Week=week(DateTime))

bbmSales %>% thead

bbmSales %>% filter(NetSales==0) %>% thead

bbmSales <- bbmSales %>% filter(NetSales!=0)

```

```{r}

g <- bbmSales %>% ggplot()+theme_classic()+
  aes(x=DateTime,weight=NetSales,col=Category)+
  geom_line(stat="bin",binwidth=int_length(300))+
  facet_wrap(~factor(str_c(DayOfYear,", weekday ",DayOfWeek)),
    scales="free",ncol=5)+
  ylab("NetSales")+xlab("5 min periods")
g

ggsave("salesThroughDay.png",g,width=10,height=07)


byItem <- bbmSales %>% group_by(Category,Item) %>%
  summarize(SumNetSales=sum(NetSales),SumQty=sum(Qty)) %>% 
  arrange(-SumNetSales)

write_tsv(byItem,path="bbm_byItem.tsv")

byItemPP <- bbmSales %>% group_by(Category,Item,`Price Point Name`) %>%
  summarize(SumNetSales=sum(NetSales),SumQty=sum(Qty)) %>% 
  arrange(-SumNetSales)

write_tsv(byItemPP,path="bbm_byItemPP.tsv")

byItemPPByWeekday <- bbmSales %>% 
  group_by(Category,Item,`Price Point Name`,DayOfWeek) %>%
  summarize(SumNetSales=sum(NetSales),SumQty=sum(Qty)) %>% 
  arrange(-SumNetSales)

write_tsv(byItemPPByWeekday,path="bbm_byItemPPByWeekday.tsv")

```
